# Project information
site_name: 'DDB-Handbuch-Vorlage'
site_description: 'Virtuelle Ausstellungen der Deutschen Digitalen Bibliothek'
site_author: 'Deutsche Digitale Bibliothek, Culture to Go & Grandgeorg Websolutions'

# Copyright
copyright: '&copy; Deutsche Digitale Bibliothek, Culture to Go, Grandgeorg Websolutions'

nav:
  - Start: index.md
  - Cheatsheet: cheatsheet.md

# Theme
theme:
  name: readthedocs
  custom_dir: themes/readthedocs_ddb
  highlightjs: False

# Options
extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  wording_next: 'vor'
  wording_previous: 'zurück'
  wording_search_docs: 'Handbuch durchsuchen'
  wording_docs: 'Kuratoren-Handbuch'
  wording_page_not_found: 'Seite nicht gefunden.'

# css
extra_css:
    - css/extra.css

# js
extra_javascript:
    - js/extra.js

# URL
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  # - codehilite:
  #     guess_lang: false
  #     linenums: false
  - footnotes
  - meta
  - toc:
      permalink: True
  - sane_lists
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - figureAltCaption


